policies:
  - name: advanced-restrict-image-registries
    rules:
      - name: validate-corp-registries
        values:
          nsregistries: "docker.io/*"
          clusterregistries.data.registries:  "docker.io/*"
          request.namespace: default
    resources:
      - name: good-pod
        values:
          request.operation: CREATE
      - name: bad-pod
        values:
          request.operation: UPDATE