version: 1.0.0
name: argo-cluster-generation-from-rancher-capi
displayName: Argo Cluster Secret Generation From Rancher CAPI Secret
createdAt: "2023-02-20T10:33:29Z"
description: This policy generates and synchronizes Argo CD cluster secrets from Rancher  managed cluster.provisioning.cattle.io/v1 resources and their corresponding CAPI secrets. In this solution, Argo CD integrates with Rancher managed clusters via the central Rancher authentication proxy which shares the network endpoint of the Rancher API/GUI. The policy implements work-arounds for Argo CD issue https://github.com/argoproj/argo-cd/issues/9033 "Cluster-API cluster auto-registration" and Rancher issue https://github.com/rancher/rancher/issues/38053 "Fix type and labels Rancher v2 provisioner specifies when creating CAPI Cluster Secret".
digest: 8b7d39da029ba7cd164f6cb8563be9be2a11f55f80497bbeb768cbf4cd5d2cd7
homeURL: https://github.com/kyverno/policies/tree/master/argo/argo-cluster-generation-from-rancher-capi
keywords:
    - kyverno
    - policy
links:
    - name: Source
      url: https://github.com/kyverno/policies/blob/master/argo/argo-cluster-generation-from-rancher-capi/argo-cluster-generation-from-rancher-capi.yaml
readme: |-
    # Argo Cluster Secret Generation From Rancher CAPI Secret
    	This policy generates and synchronizes Argo CD cluster secrets from Rancher  managed cluster.provisioning.cattle.io/v1 resources and their corresponding CAPI secrets. In this solution, Argo CD integrates with Rancher managed clusters via the central Rancher authentication proxy which shares the network endpoint of the Rancher API/GUI. The policy implements work-arounds for Argo CD issue https://github.com/argoproj/argo-cd/issues/9033 "Cluster-API cluster auto-registration" and Rancher issue https://github.com/rancher/rancher/issues/38053 "Fix type and labels Rancher v2 provisioner specifies when creating CAPI Cluster Secret".
install: |-
    ### Usage
    ```shell
    kubectl apply -f https://raw.githubusercontent.com/kyverno/policies/master/argo/argo-cluster-generation-from-rancher-capi/argo-cluster-generation-from-rancher-capi.yaml
    ```
provider:
    name: kyverno
