version: '%!s(<nil>)'
name: generate-flux-multi-tenant-resources
displayName: Generate Flux Multi-Tenant Resources
createdAt: "2023-02-19T19:27:48Z"
description: As part of the tenant provisioning process, Flux needs to generate RBAC resources. This policy will create a ServiceAccount and RoleBinding when a new or existing Namespace is labeled with `toolkit.fluxcd.io/tenant`. Use of this rule may require an additional binding for the Kyverno ServiceAccount so it has permissions to properly create the RoleBinding.
homeURL: https://github.com/Ashwin901/policies/tree/master/flux/generate-flux-multi-tenant-resources
keywords:
    - kyverno
    - policy
links:
    - name: Source
      url: https://github.com/Ashwin901/policies/blob/master/flux/generate-flux-multi-tenant-resources/generate-flux-multi-tenant-resources.yaml
readme: |-
    # Generate Flux Multi-Tenant Resources
    As part of the tenant provisioning process, Flux needs to generate RBAC resources. This policy will create a ServiceAccount and RoleBinding when a new or existing Namespace is labeled with `toolkit.fluxcd.io/tenant`. Use of this rule may require an additional binding for the Kyverno ServiceAccount so it has permissions to properly create the RoleBinding.
install: |-
    ### Usage
    ```shell
    kubectl apply -f https://raw.githubusercontent.com/Ashwin901/policies/master/flux/generate-flux-multi-tenant-resources/generate-flux-multi-tenant-resources.yaml
    ```
provider:
    name: Ashwin901
