policies:
  - name: unique-external-dns
    rules:
      - name: ensure-valid-externaldns-annotation
        values:
          alldns: "[\"test.external-dns-test.my-org.com\"]"
    resources:
      - name: good-svc
        values:
          request.operation: CREATE
      - name: bad-svc
        values:
          request.operation: UPDATE