apiVersion: v1
kind: Pod
metadata:
  name: good-pod
spec:
  containers:
  - image: gcr.io/hello-world:1.0
    name: test
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "2Gi"
    volumeMounts:
    - mountPath: /cache/data
      name: vol
  volumes:
  - name: vol
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
spec:
  containers:
  - image: gcr.io/hello-world:1.0
    name: 
    volumeMounts:
    - mountPath: /cache/data
      name: vol
  volumes:
  - name: vol
    emptyDir: {}