apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.1
    volumeMounts:
    - mountPath: /var/local/aaa
      name: mydir
  volumes:
    - name: mydir
      emptyDir: {}

---

apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.1
    volumeMounts:
    - mountPath: /var/local/aaa
      name: myfile
  volumes:
    - name: myfile
      hostPath:
        path: "*"
