apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-good-ingress
spec:
  tls:
  - hosts:
      - https-example.foo.com
    secretName: testsecret-tls
  rules:
  - host: https-example.foo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tls-bad-ingress
spec:
  tls:
  - hosts:
      - https-example.bad.com
    secretName: testsecret-tls-bad
  rules:
  - host: https-good.good.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80