apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example
  namespace: default
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: firstname
    remoteRef:
      key: default-remote-secret
      property: "name.first" # Tom
  - secretKey: first_friend
    remoteRef:
      key: default-remote-secret
      property: "friends.1.first" # Roger