policies:
  - name: only-trustworthy-registries-set-root
    rules:
      - name: only-allow-trusted-images
        values:
          imageData.registry: "ghcr.io"
          imageData.configData.config.User: "root"
          
    resources:
      - name: pod-with-trusted-registry
        values:
          request.operation: CREATE
      - name: pod-with-root-user
        values:
          request.operation: UPDATE
         