apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-clusterrole-wildcard
  annotations:
    policies.kyverno.io/title: Restrict ClusterRole with Wildcards
    policies.kyverno.io/category: Sample
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: ClusterRole, RBAC
    kyverno.io/kyverno-version: 1.7.0
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/description: >-
      A ClusterRole with wildcard resource access allows anything
      under the specified API group to be covered. This can lead to
      far too broad of permissions and should be carefully controlled.
      This policy enforces that any ClusterPolicy does not use a wildcard
      under resources.
spec:
  validationFailureAction: audit
  background: true
  rules:
    - name: clusterrole-wildcard
      match:
        any:
        - resources:
            kinds:
              - ClusterRole
      validate:
        message: "A ClusterRole using a wildcard for resources is not allowed."
        deny:
          conditions:
            any:
            - key: "{{ contains(request.object.rules[].resources[], '*') }}"
              operator: Equals
              value: true