apiVersion: v1
kind: Pod
metadata:
  name: withoutinitcontainer
spec:
  automountServiceAccountToken: false
  containers:
  - name: nginx
    image: nginx:1.2.3
  - name: redis
    image: redis:latest