policies:
- name: prepend-registry
  rules:
  - name: prepend-registry-containers
  - name: prepend-registry-initcontainers
  resources:
  - name: mypod
    values:
      request.operation: CREATE
  - name: myfailedpod
    values:
      request.operation: CREATE
  - name: withoutinitcontainer
    values:
      request.operation: CREATE