name: Policy Test

on:
  push:
    branches:
      - main
      - release*
  pull_request:
    branches:
      - main
      - release*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
        with:
          path: policies

      - name: Clone Kyverno
        run: |
          if [[ ${{ github.event_name }} == "push" ]]
          then
            GIT_BRANCH=${GITHUB_REF##*/}
          elif [[ ${{ github.event_name }} == "pull_request" ]]
          then
            GIT_BRANCH=${{ github.event.pull_request.base.ref }}
          fi

          git clone https://github.com/kyverno/kyverno --branch $GIT_BRANCH

      - name: Set up Go 
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: 1.17

      - name: Test Policy
        run: |
          cd kyverno
          go run cmd/cli/kubectl-kyverno/main.go test ../policies